ALTER TABLE savings_contributions
  ALTER COLUMN period_year SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::SMALLINT,
  ALTER COLUMN period_month SET DEFAULT EXTRACT(MONTH FROM CURRENT_DATE)::SMALLINT;
